### ISSUE TITLE
License in package.json differs from package-lock.json

### ISSUE THREAD

**Issue by gxclarke** [h5p/h5p-editor-vertical-tabs#7]
This issue was initially reported here: https://github.com/h5p/h5p-cli/issues/119#issuecomment-2422970987

It is causing the h5p CLI command to fail. Could you please fix it? I'm happy to submit a PR if that is preferable.

**Comment by otacke** [comment]
@gxclarke Where exactly is H5P CLI failing? Yes, this will create an unstaged change when setting up the editor widget - but I don't see where this should cause trouble for H5P CLI.

**Comment by gxclarke** [comment]
@otacke Reviewing the code, I suspect it is failing at https://github.com/h5p/h5p-cli/blob/3e3c9122168afed6105fc18aa65d88367ee194d8/logic.js#L393

It causes trouble for the H5P CLI because it errors out at this point. I realize this wasn't obvious from my issue explanation, so I added a comment there with additional details.

**Comment by otacke** [comment]
@gxclarke Sorry, can't reproduce this on my end. `h5p setup h5p-course-presentation` does its job just file here, even if run multiple times with the `h5p-editor-vertical-tabs` library having been build in the first run.

@devland is the main developer of the H5P CLI tool (I am not a member of the H5P core team). Maybe he can reproduce the issue.

**Comment by gxclarke** [comment]
I think I see why you can't reproduce it. In my environment, I have set git to rebase by default when pulling:

`git config --global pull:rebase true`

I had forgotten that this setting was configured until debugging this h5p issue clued me in.

@otacke Thank you for trying to reproduce it. Knowing that it could not be reproduced by another person helped narrow down potential reasons.

I'll close this issue. Hopefully, it may help someone else in the future.

**Comment by otacke** [comment]
@gxclarke You're welcome. Maybe @devland is going to think about calling git with `-c pull:rebase false` to rule out those issues.
